version: "3.9"

services:
  web:
    build:
      context: ..                    
      dockerfile: Dockerfile
    container_name: fastapi_app
    restart: unless-stopped
    env_file:
      - ../.env                      
    environment:
      - DATABASE_URL=${DATABASE_URL:-postgres://postgres:postgres@db:5432/appdb}
      - PYTHONUNBUFFERED=1
    volumes:
      - ../:/app                     
      - ../logs:/app/logs            
    ports:
      - "8000:8000"                 
    depends_on:
      - db
    command: >
      sh -c "uvicorn app.main:app
            --host 0.0.0.0
            --port 8000
            --reload"

  db:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-appdb}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    container_name: adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  db_data: {}